# Generated by Django 5.0.7 on 2025-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_remove_movie_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No Description Available'),
            preserve_default=False,
        ),
    ]
